name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load FTP config
        id: config
        run: |
          # ローカルディレクトリの読み込み
          LOCAL_DIR=$(cat .github/workflows/config/ftp-config.yml | grep "local_dir:" | cut -d ":" -f 2- | xargs)
          echo "local_dir=$LOCAL_DIR" >> $GITHUB_OUTPUT
          
          # 除外パターンの読み込み
          EXCLUDE_PATTERNS=$(cat .github/workflows/config/ftp-config.yml | grep -A 100 "exclude_patterns:" | tail -n +2)
          echo "patterns<<EOF" >> $GITHUB_OUTPUT
          echo "$EXCLUDE_PATTERNS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: FTP Deploy to Production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          server-dir: ${{ secrets.PROD_FTP_SERVER_DIR }}/
          local-dir: ${{ steps.config.outputs.local_dir }}
          dangerous-clean-slate: false
          state-name: .ftp-deploy-sync-state-prod.json
          exclude: ${{ steps.config.outputs.patterns }}